### ISSUE TITLE
Providing pre-compiled binaries

### ISSUE THREAD

**Issue by TheL1ne** [alueck/POE-TradeHelper#42]
Hello, I just found your repo via a searchengine and wanted to try your project out. Now I am downloding an IDE. Maybe you could provide a pre-compiled binary so users would be able to just download and start the program? WOuld be really great :)

**Comment by TheL1ne** [comment]
Short update: I tried installing dotnet SDK and I could build your project but I am unable to run it. unfortunatly I never interacted with .Net even though I do program for a living :-/

**Comment by alueck** [comment]
Sorry, I did not get any notification about your comment. The releases are published as pre-releases on the [Releases Page](https://github.com/alueck/POE-TradeHelper/releases). I just created a new one, because the latest did not contain some bugfixes. As seen in the commit history, I am not really actively developing this project at the moment though. It should still work fine for most of the item types, but there will certainly be some bugs I myself have not found yet.
